### PR TITLE
flac: add preliminary flac decoder

### PR DESCRIPTION
**Pull request by mewmew**
As noted in https://github.com/zikichombo/codec/issues/3#issuecomment-411453417
there are some bugs to be ironed out.

Updates #3.

### CODE REVIEW

**Comment by mewmew** [comment]
@wsc1 Perhaps wait to merge this until we can iron out the known issue.

**Comment by mewmew** [comment]
@wsc1 FYI, the mewkiz/flac library now provides support for encoding FLAC streams (see https://github.com/mewkiz/flac/pull/32). An encoder for zc could easily be added.

**Comment by wsc1** [comment]
This is very good news!  It must have been a lot of work, with all the quantisation of lpc COEFS and everything.

**Comment by mewmew** [comment]
> This is very good news! It must have been a lot of work, with all the quantisation of lpc coefs and everything.

Haha, yes. It would have been a lot of work, with LPC for sure! The PR adds basically WAV verbatim encoding for FLAC streams. There are four predictions methods used in FLAC
- [ ] constant
- [x] verbatim
- [ ] fixed: LPC with coefficients from a fixed set of polynomials
- [ ] FIR: LPC with coefficients stored in 0th to 32nd order prediction polynomials.

Only verbatim is implemented now. Mainly to get the API right. Constant would be trivial to implement. LPC requires much more work, as you pointed out.

**Comment by wsc1** [comment]
Does the decoder do all the modelling methods?

**Comment by mewmew** [comment]
> Does the decoder do all the modelling methods?

What do you mean by modelling methods?

**Comment by wsc1** [comment]
I mean prediction methods (lpc "fixed/FIR")?

**Comment by mewmew** [comment]
The decoder handles all prediction methods (LPC "fixed/FIR"). The encoder however, only handles constant and verbatim (for now).

**Comment by wsc1** [comment]
Great news!

For the encoder, It may help us here at zc to hear about and/or help with how the FLAC lpc prediction is done.  The zc/dsp/lpc module should be capable of doing the lpc part, although it's implementation is not the same as nor (yet) as fast as the FLAC one, so you probably wouldn't get exactly the same coefficiencts all the time.  Not sure if you already have the modelling part of lpc in your decoder, as it's not strictly necessary for decoding.  It would also help us to learn more about the subtleties around quantization of lpc coefficients, as a straightforward dumb quantisation won't work as well as what FLAC has, and there are publications around that topic of interest as well.

If you would be interested in sharing that journey, let us know when and how,  fwiw, here or via mail or in another issue, would work for us.

**Comment by wsc1** [comment]
@mewmew 

For info, I have added a function  sound/cil.Compact which can make it easier to handler EOF.

**Comment by mewmew** [comment]
> What would you think of having a zc wrapper that imports zc and mewkiz flac in an "ext" repository under the zikichombo github organisation?

Sure, we can try it out.

**Comment by wsc1** [comment]
Great,

I'm new to using github to organise this kind of stuff...

I created a repo "github.com/zikichombo/ext" and a dedicated team under github.com/zikichombo
and sent you an invite to the team.

**Comment by wsc1** [comment]
This PR has been moved to https://github.com/zikichombo/ext/pull/2 since it imports both zc and outside zc

**Pull request closed without merging**
